### ISSUE TITLE
Option to remove/disable DIR arrows (space)

### ISSUE THREAD

**Issue by tuberry** [preservim/nerdtree#1064]
#### Description
I've followed the discussion in #636 to set the arrows invisible, but how could I remove the remained space? It looks too spacious when integrating with [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) and [devicons](https://github.com/ryanoasis/vim-devicons). Thanks!
![nredtree](https://user-images.githubusercontent.com/17917040/69904888-9bc56700-13e7-11ea-9aa1-7d9c9f9e290d.png)
Thanks!!

**Comment by PhilRunninger** [comment]
@tuberry After considering for a long time to reject this request, I had a change of heart, and decided to give this a go. Turns out it was easier than I'd expected. I have a pull request (#1085) out, whose branch I'd like you to test. This is not complete; syntax highlighting still needs work, and there may be some other errors related to the change of indentation. To turn on this new feature, add (or change) these .vimrc lines:
```vim
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
```
These empty strings will eliminate the arrows and their single trailing space, and will decrease files' indentation by two characters. Please report any issues with and without [vim-devicons](https://github.com/ryanoasis/vim-devicons) or [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) being installed.
