### ISSUE TITLE
Root directory action bind

### ISSUE THREAD

**Issue by riser88** [preservim/nerdtree#1082]
Hi,

I was searching for answer, but I was not able to find it.

When I click ENTER on the root directory I have following error
> NERDTree: cannot close tree root

Beside manual editing source code is there any option to change interaction with root directory ?
For example instead of "closing root directory" I would like to change it by one level like it's done with "Shift+u" bind.

**Comment by PhilRunninger** [comment]
No, there is no way to do what you're asking to do. The Enter key's behavior can be modified a bit (see `:h NERDTreeCustomOpenArgs`), but all directories are treated the same way. For obvious reasons, we don't allow the root to be collapsed, which is why you see that error message.

Different commands are given specifically so that different actions can be taken. One should not attempt or expect to have one key do everything. The best solution is, as you mentioned, to use the `u` or 'U' key.
