### ISSUE TITLE
How to customize a mapping (e.g. map <CR> to preview rather than open)? 

### ISSUE THREAD

**Issue by jan-warchol** [preservim/nerdtree#1123]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I would like to customize NERDtree so that pressing Enter opens a file without switching to it. I tried 3 methods and none worked:
```
autocmd FileType nerdtree nnoremap <buffer> <CR> go
```
```
let g:NERDTreeMapPreview = "<CR>"
```
```
call NERDTreeAddKeyMap({
	\ 'key': '<CR>',
	\ 'callback': 'NERDTreeMapPreview',
	\ 'quickhelpText': 'preview current file' })
```
How to achieve this?

**Comment by PhilRunninger** [comment]
The `Enter` key works a little bit differently. By default, it's set up to mimic the `o` key, but that can be changed by setting a variable in your `.vimrc`. There are two sections of the help file that talk about it. See `:h NERDTree-<CR>` and `:h NERDTreeCustomOpenArgs`. The setting you'll need is:

```vim
let NERDTreeCustomOpenArgs = {'file':{'where':'p','keepopen':1,'stay':1}}
```

**Comment by jan-warchol** [comment]
Ah, thanks! Very nice! I'm curious why I didn't find it in the docs :thinking: 
Anyway, what about remapping other keys? I tried mapping `y` to do what `go` does (using each of the techniques listed in the first post) and it seems not to work...

**Comment by PhilRunninger** [comment]
Your first method fails because you're using `nnoremap`. This causes Vim to execute its native `go` command, not the `go` mapping that NERDTree setup. To fix this, use: `autocmd FileType nerdtree nmap <buffer> y go`

The second method is working for me. Make sure you don't have the previous method in place at the same time. There is some interference there I haven't quite figured out.

The third method won't work until you write a function called `NERDTreeMapPreview()`. It must follow a specific pattern, as described in the `NERDTreeAddKeyMap` documentation. I recommend against this method, because you're not writing new functionality, and the second method already is part of the NERDTree machinery.

**Comment by jan-warchol** [comment]
It works indeed! Thanks for explanations! :-)
