### ISSUE TITLE
How can I change which keys to press to navigate up and down the list? Docs coundn't help.

### ISSUE THREAD

**Issue by angarc** [preservim/nerdtree#1141]
Sorry if I'm not giving enough info, but I really wouldn't consider this an issue. This is just me having trouble because of ignorance.

#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I use the Colemak keyboard layout instead of QWERTY, so I'd like to change the keybindings so that I can navigate up and down through the nerdtree using 'n' and 'e' instead of 'j' and 'k'. According to the docs, I'm supposed to write this in my vimrc:

let g:NERDTreeMenuDown = 'n'
let g:NERDTreeMenuUp = 'e'

Navigating down with 'n' works but navigating up with 'e' does not work. Instead, it just opens up another nerdtree window in vim. 

I would appreciate it if you could tell me what I'm doing wrong, thanks!

**Comment by PhilRunninger** [comment]
That depends on what you mean by 'list'. The variables you reference - `g:NERDTreeMenuDown` and `g:NERDTreeMenuUp` - are for the NERDTree menu, which you would access with the default key `m`, or whatever the value of `g:NERDTreeMapMenu` is. This menu provides access to file system commands, and can be extended with code in your `.vimrc` or other plugins. There doesn't appear to be any conflict in this menu.

If the list you are referring is the tree of files and directories, then the variables you mention are not applicable. By default, the `e` key is assigned to the `NERDTreeMapOpenExpl` variable, which will open a new NERDTree or netrw buffer, by design. Navigating the tree is done with standard Vim movement keys - `j`, `k`.

I imagine getting Vim to work with the Colemak keyboard requires remapping a bunch of keys, especially if you want the arrow keys to stay on the home row. If you've already done this:
```vim
nnoremap n j
nnoremap e k
```
then you just need to disable, or reassign `e` in NERDTree. I never use the `e` key in NERDTree, so disabling works for me:
```vim
let g:NERDTreeMapOpenExpl = ''
```
but if you want that functionality, you can assign another key to it.

**Comment by angarc** [comment]
Yep, that worked for me! Thanks!
