### ISSUE TITLE
Open two buffers at the same window and then closing one, exits vim

### ISSUE THREAD

**Issue by dr-costas** [preservim/nerdtree#1147]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: macOS 10.15.5
- [ ] Vim/Neovim version `:echo v:version`: 802
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.13
- [ ] vimrc settings
    - [ ] NERDTree variables: Default
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Use a clean .vimrc file with Vim-plug
2. Use the minimal vimdc file: 
    ```vim
    set nocompatible
    filetype plugin indent on
    call plug#begin('~/.vim/plugged')
    Plug 'scrooloose/nerdtree'
    call plug#end()
    ```
3. In terminal, create two files: 
    ```bash
    $ touch file_a
    $ touch file_b
    ```
4. Open vim
5. From NERDTree open `file_a` (or by using `:edit file_a`)
6. From NERDTree open `file_b` (or by using `:edit file_b`)
7. Close the top buffer at the window with either `:bd` or `:bw`
8. Vim exits. This is not normal behavior, because using `vim -u NONE -U NONE -N` and doing steps 3, 4, 5 & 6 (ofc with `:edit`), and 7, removes only the top buffer. 

#### Expected Result
Using `vim -u NONE -U NONE -N` and doing steps 3, 4, 5 & 6 (ofc with `:edit`), and 7, removes only the top buffer. 

Even with 

````vim
set nocompatible
filetype plugin indent on
call plug#begin('~/.vim/plugged')
call plug#end()
````

the behavior is same as with `vim -u NONE -U NONE -N`. 

Finally, question is related to #301 but the solution proposed is to switch buffers and then delete. But:

1. This solution (i.e. using `:bp <cr>:bd<cr>`) has the same effect of vim exiting
2. I want to have the typical behavior with `:bd` and `:bw`.

**Comment by PhilRunninger** [comment]
I am not seeing this behavior. Your minimal `vimrc` file is working for me as you expect it to. I tried the following:

1. `:edit file_a`
1. `:edit file_b`
1. `:bw`  This closes `file_b`
1. Vim is still open with `file_a` showing in the editor.

Strange, but expected, behavior happens when I use NERDTree, but it still doesn't close vim:

1. `:NERDTree`
1. open both `file_a` and `file_b`
1. Keep NERDTree open.
1. Go to the `file_b` window.
1. `:bw`
1. Vim is still open, but the window with `file_b` in it was closed, leaving only NERDTree visible.

I also tried it by using Vim 8+ packages instead of vim-plug, and got the same results.

Try doing `:debug bw`, and see if any autocommands are causing the isssue.

**Comment by dr-costas** [comment]
@PhilRunninger 

> Vim is still open, but the window with file_b in it was closed, leaving only NERDTree visible.

Have you tried to have both files in the same window? Because this is when the problem happens. If the two files are in different windows, then the problem is not happening.

**Comment by PhilRunninger** [comment]
Yes, there were two windows: one for NERDTree, and the other displaying `file_b`. With the cursor in the `file_b` window, `:bw` deletes the buffer and closes the window just like the Vim documentation describes. The remaining window goes full screen with NERDTree in it.

**Comment by dr-costas** [comment]
Still, that is not what I'm describing. 

You should have two windows. `window 1` with NERDTree, and `window 2` with two open buffers, for `file_1` and `file_2`. That is, `window_2` should have both `file_1` and `file_2`. Then, if you do `:bd` or `:bw` to one of the buffers of `file_1` or `file_2`, Vim will exit.

**Comment by dr-costas** [comment]
To describe again the scenario. 

1. Open Vim. 
2. If NERDTree is not open/toggled on, open it. 
3. From NERDTree open one file, i.e. `file_a`, with 'o' in a window, i.e. `window_1`. 
4. Again from NERDTree, open another file, i.e. `file_b`, again with 'o' (i.e. at the same window as `file_a`, the `window_1`). 
5. While the cursor is at `window_1`, do `:bw`. 

Vim will exit, which is not the expected behavior.

**Comment by PhilRunninger** [comment]
That's what I did. Vim does not exit. Try the `:debug bw` command. In the debugger, use the `s` command to step through the statements.  Take note of what autocommand or script is running when Vim exits.

**Comment by cxgslegend** [comment]
I personally don't mind this, but it also happens for me. If I had to guess why it's happening. It's because of the standard auto command that nerdtree recommends to close vim if nerdtree is the only open buffer. When I remove this autocommand, I don't get this behavior anymore. Which would explain why you don't see this with his minimal vimrc. 

```
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
```

My guess is that when you delete the top buffer, it begins opening the previous buffer, but winnr("$") will still report 1, because you are just entering the buffer from its perspective. So this would trigger the autocommand to quit. 

Personally, I always switch to my previous buffer with a `<c-^>` mapping. Or I just use fzf to search for a buffer. But if this functionality is critical to your workflow, I guess you could modify the autocommand to count the open buffers or something.

**Comment by dr-costas** [comment]
@cxgslegend 

Can you please tell me how to remove this autocommand? Because I cannot see it in my *rc file.

**Comment by dr-costas** [comment]
I think I found it. 

It was another plugin, which (for some reason) when I removed it, I had to exit the terminal session and then open a new one in order for the effect of the problematic plugin to go away. 

Plugin is the: 

https://github.com/jistr/vim-nerdtree-tabs

When I installed it, the unexpected behavior appeared. If, in the same terminal session, I uninstalled the plugin, the behavior would not go away. I had to close the terminal session and open another. This is why I could not find that this was the problem and this is why @PhilRunninger could not see the effect. 

Thank you both though. If I had not your feedback, I would not have searched it more.
