### ISSUE TITLE
Just updated. Every tab I close shrinks the file explorer to the default width

### ISSUE THREAD

**Issue by towens** [preservim/nerdtree#1176]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
Probably a setting... I'm used to `shift + A` expanding the file explorer and not thinking about it again. Now, any opened tab causes the file explorer to shrink in width to the default.

I didn't go through them all, anything passed tag 5.0.0 seems to exhibit the issue.

**Comment by PhilRunninger** [comment]
@towens, you left a lot of context out of your question, so I have to guess how this can be reproduced. Since you mentioned tabs, I assume that you are opening NERDTree, using `t` to open the selected file in a new tab, and then opening NERDTree again in the new tab. If that assumption is incorrect, please add some more detail to the issue. 

Here is what I know/discovered:

1. The NERDTree buffer's width is remembered each time it closes, so that it can be set to that width when it's opened again. So if you open a file in the same tab, with the `o` key, the next time NERDTree is opened, it will still be expanded.
1. Opening NERDTree with the `:NERDTree` command in a new tab will create a new NERDTree buffer. Since it's new, it will open in the narrow state.
1. You can use the `:NERDTreeMirror` command to open the same NERDTree you had in the first tab. This should work, and open it in the expanded state, but there is a bug that I discovered. NERDTree knows the window is supposed to be expanded, but it is being rendered as a narrow window. Pressing `A` once does nothing, because that is supposed to shrink the window (which is already shrunk). Pressing `A` the second time expands it.

I will address the bug in the third bullet. If you have another scenario, please describe it in detail in the issue.

**Comment by towens** [comment]
@PhilRunninger, thanks for bringing up context. I will only have one instance of NERDTree open per tmux session, and you are correct, I open all files by pressing the `t` key. It's possible my `.vimrc` is no longer compatible with the latest release. The relevant settings.

```
" NERDTree
let NERDTreeShowHidden=1
let NERDTreeNaturalSort = 1
set switchbuf=useopen,usetab

" open NERDTree unless you specify a file name
autocmd StdinReadPre * let s:std_in=1 
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif 
```

**Comment by PhilRunninger** [comment]
Your settings are OK, although `switchbuf` has no effect on what NERDTree does. That setting controls how Quickfix commands work, and NERDTree doesn't use any of those commands.

You also need to add `let NERDTreeQuitOnOpen = 1` in order to see the issue I referred to.  If set to 0 (the default), NERDTree will unzoom when opening a file so more room is given to the file that was just opened. But when set to 1, NERDTree closes after opening a file, and it remains zoomed the next time it's opened.

To make mirroring the NERDTree in a new tab easier, you can use a mapping like the one below. It will automatically mirror the NERDTree before opening it.
```vim
nnoremap <silent> <C-N> :NERDTreeMirror<CR>:NERDTreeFocus<CR>
```

Checkout branch `i1176` and see if it solves your issue. That branch fixes the `:NERDTreeMirror` command so that it displays an already-zoomed NERDTree correctly.
