### ISSUE TITLE
Focusing already opened tab with "t", similar behavior of "enter"

### ISSUE THREAD

**Issue by JpOnline** [preservim/nerdtree#1198]
#### Description

When I press "t" in a file it opens in a new tab. When I go back to nerdtree and press "enter" in the same file it recognizes the file is already opened and just focus the tab. If I go back to nerdtree and press "t" in the same file it opens a second tab for the same file.

How can I tweak the code so the "t" has a similar behavior than "enter" (of a already opened tab)? i.e. focusing the tab instead of opening a new one.

**Comment by PhilRunninger** [comment]
This is by design. Many times it's helpful to have different layouts on different tabs. For example, one tab could be for development, showing a controller and a view, and the other tab could be for debugging, with the controller and a log file. NERDTree facilitates that arrangement by allowing you to open the controller in a second tab while it's already open in the first.

If you want to go with the one-buffer-per-tab paradigm, you could tweak your NERDTree settings in your `vimrc` to accomplish it. While `o` is considered to be the official keystroke to open a file, `Enter` offers more flexibility. It is the Custom Open keystroke, so named because you, the NERDTree user, can specify how it opens files. If you put the following line in you `vimrc`, you could maybe use `Enter` exclusively. It will jump to a file no matter where it's being displayed, and if not already open, it will open the file in a new tab. `Enter`'s default behavior is to open a file in the current tab, or jump to a window containing it, just like the `o` key.
```vim
let NERDTreeCustomOpenArgs = {'file':{'reuse':'all', 'where': 't'}}
````
Check out `:h NERDTreeCustomOpenArgs` for more details about this setting.

**Comment by jsit** [comment]
Hm I don't think this quite solves the problem described. What I think @JpOnline is after isn't "one-buffer-per-tab", but "one-window-per-buffer".

The same behavior can be seen if you press `s` for a vertical split, which keeps creating split windows instead of using the existing window.

If I have four windows in tab 2, and they include `readme.md`; and I'm currently focused on tab 1; and I press `t` in NERDTree (or enter, or `s`, etc.); the desired behavior is moving focus to the window in tab 2 that already has the buffer with that file open.
