### ISSUE TITLE
Add an option to limit the number of display files

### ISSUE THREAD

**Issue by gVimer** [preservim/nerdtree#1199]
#### Description

We know that when there are too many files, the plug-in is slow to display. Can you add an option to stop displaying when the number of files exceeds this value, which can increase the speed of the plug-in

**Comment by gVimer** [comment]
like this:let g:NERTreeShowFilesMaxCount=50
`function! s:TreeDirNode._initChildren(silent)
    "remove all the current child nodes
    let self.children = []

    let files = self._glob('*', 1) + self._glob('.*', 0)

    if !a:silent && len(files) > g:NERDTreeNotificationThreshold
        call nerdtree#echo('Please wait, caching a large dir ...')
    endif
    let EXENameDIC={} 
    for i in g:NERDTreeIgnore
        let EXENameDIC[toupper(i)]=1
    endfor
    let invalidFilesFound = 0
    let nCount=0
    for i in files
        let FileEXEName=toupper(strpart(i,strridx(i,".")))
        if (isdirectory(i) || get(EXENameDIC,FileEXEName,0)==0) && nCount-invalidFilesFound<=g:NERTreeShowFilesMaxCount
            let nCount=nCount+1
            try
                let path = g:NERDTreePath.New(i)
                call self.createChild(path, 0)
                call g:NERDTreePathNotifier.NotifyListeners('init', path, self.getNerdtree(), {})
            catch /^NERDTree.\(InvalidArguments\|InvalidFiletype\)Error/
                let invalidFilesFound += 1
            endtry
        end
    endfor

    let g:NERDTreeOldSortOrder = g:NERDTreeSortOrder
    call self.sortChildren()

    call nerdtree#echo('')

    if invalidFilesFound
        call nerdtree#echoWarning(invalidFilesFound . ' file(s) could not be loaded into the NERD tree')
    endif
    return self.getChildCount()
endfunction
`

**Comment by PhilRunninger** [comment]
No, I won't be doing this. 

1. It doesn't solve the problem, because you would have the same slow response in NERDTree by opening many folders that have your minimum of 50 files.
2. It will cause confusion and frustration when the file someone wants to open is number 51.
3. It is just a workaround for poor file management. There is simply no reason to have hundreds of files in a single folder. There are exceptions, but often (as in the case of `node_modules`) you can add them to your `NERDTreeIgnore` list.
4. To fix the the slowness issues properly, NERDTree would have to abandon its object-oriented approach, which is very slow in the Vimscript language. That is a large project that I have no interest in pursuing.

If a NERDTree becomes slow, it will never speed up. If you experience this, you can revive it by wiping out that buffer and restarting NERDTree.
```vim
:bwipeout
:NERDTree
```
