### ISSUE TITLE
Ignore subdirectories

### ISSUE THREAD

**Issue by RobertAudi** [preservim/nerdtree#1203]
#### Description

At the moment the `NERDTreeIgnore` allows to ignore files and directories by matching the last path component:

https://github.com/preservim/nerdtree/blob/aaa946fb6bd79b9af86fbaf4b6b63fd81d839bd9/lib/nerdtree/path.vim#L498

So the following will not work:

```vim
let NERDTreeIgnore = ['tmp/cache$[[dir]]']
```

It would be nice if we could specify paths to ignore. Something like that would not change the current behavior (it would just add to it):

```vim
let NERDTreeIgnore = ['tmp/cache$[[path]]']
```

**Comment by PhilRunninger** [comment]
@RobertAudi, You can checkout the branch named #i1203. It has your request in it. Give it a try, and let me know how it works for you.

**Comment by RobertAudi** [comment]
@PhilRunninger I just tried it and it works perfectly.

I was going to say it didn't seem to work, but then I modified the pattern. The problem was that unlike `[[file]]` and `[[dir]]` you should't use `$` otherwise it only match directories without anything inside.

Anyway, it works perfectly!

**Comment by PhilRunninger** [comment]
@RobertAudi could you tell me a scenario where you'd use this in place of the existing tags? I need some inspiration for the help documentation.

The reason your pattern didn't work with the `$` is because I was using the UI-formatted path, which has a trailing forward slash on it, such as `/tmp/cache/`, which doesn't match the regex `/tmp/cache$`. I pushed another change to correct that, if you want to give it another go. FYI, the Windows equivalent pattern would need to be specified like so, with escaped backslashes:
```vim
let NERDTreeIgnore = ['\\Temp\\cache$[[path]]']
```

**Comment by RobertAudi** [comment]
> could you tell me a scenario where you'd use this in place of the existing tags? I need some inspiration for the help documentation.

@PhilRunninger I sometimes put temp files in `tmp`, for example files where I put stuff that I will reuse. However there are often other directories in the `tmp` directory such as `cache` or `pids` that either have huge amount of files and/or unreadable files, and if the directory node is opened it will slow down the whole editor to load its contents in the tree.

Another such example is `vendor/cache` in Ruby/Rails projects with vendor gems cached by bundler.
