### ISSUE TITLE
Can :e /directory/ open NERDTree and not netrw?

### ISSUE THREAD

**Issue by lesar** [preservim/nerdtree#1204]
I use the readme.md code example to open a directory using command like:  
```bash
$ vim /directory/
```
and work well.  

but if I open vim and then do `:e /directory/` the folder is open using netrw instead NERDTree.  
I have put `let g:NERDTreeHijackNetrw = 0`: if I set to 1 NERDTree is closed if I hit <CR> on a file on it and I not like that.  

There is a way to make `:e /directory/` work like `$ vim /directory/`?

best regards,
Leonardo

**Comment by PhilRunninger** [comment]
I can only speculate, since I wasn't around at the beginning of NERDTree, but I think the two styles of NERDTree were done so that there would be one that behaves like netrw's `:Explore` command. Your question indicates you would like NERDTree to always create a split window, and show up there. I have considered removing the WindowTree style, as it's called, but I suspect there might be some resistance to it.

One way to do what you're asking is with the command abbreviation `:cnoreabbrev e NERDTree`, but that would break the `:e` command for times you want to open a file. It would change `:e foo.txt` to `:NERDTree foo.txt`, and NERDTree would complain. There may be other ways, but I can't think of any right now.

**Comment by lesar** [comment]
My workaround is to modify a plugin that do `:e /directory/` hard-code into it `:NERDTree /directory/`  in new buffer.  
best regards,
Leonardo
