### ISSUE TITLE
Python indentation plugin doesn't work with Nerdtree

### ISSUE THREAD

**Issue by vidakDK** [preservim/nerdtree#1244]
#### Self-Diagnosis

- [x ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x ] I have searched the web for an answer to my question.

#### State Your Question
I have a Vim plugin for indentation with Python files that works when I open a file directly with `vim foo.py`, but when I open it with Nerdtree the plugin doesn't work, e.g. when I open a file in split screen with `s` from Nerdtree. 

Do you have an idea how I could activate the plugin also from Nerdtree? Here's the code of the Python plugin: https://github.com/vim-scripts/indentpython.vim/blob/master/indent/python.vim

Thanks!

**Comment by PhilRunninger** [comment]
@vidakDK, let's find out which scripts are being called when you open `foo.py`. The `:scriptnames` command, I think, will be useful here. When I run it before opening `foo.py` with NERDTree, I see a list of 94 scripts. Then again after opening `foo.py`, I see these additional ones:
```
95: C:\tools\neovim\Neovim\share\nvim\runtime\ftplugin\python.vim
96: ~\AppData\Local\nvim\pack\extra\opt\indentpython.vim\indent\python.vim
97: C:\tools\neovim\Neovim\share\nvim\runtime\indent\python.vim
98: C:\tools\neovim\Neovim\share\nvim\runtime\syntax\python.vim
```
This shows that the [indentpython.vim plugin](https://github.com/vim-scripts/indentpython.vim/blob/master/indent/python.vim) is being called first. The one included with Neovim is called second, but because `b:did_indent` is already set, it finishes without doing anything. So, it's working correctly on my machine.

Using `vim foo.py`, I see the same behavior. It just takes more patience to find the indent scripts in the `:scriptnames` output.

If the two indent scripts are in the opposite order, I wonder what could be causing that. First things first. What do you see when you run the `:scriptnames` command?

**Comment by PhilRunninger** [comment]
@vidakDK , I'm closing this issue because I haven't heard back from you. Feel free to reopen with the requested information.
