### ISSUE TITLE
Show files in remote server via scp

### ISSUE THREAD

**Issue by marcelned** [preservim/nerdtree#1255]
Currently NERDtree shows the localhost's filestructure when `vim scp://user@remotehost//somefile` is invoked.

**Comment by PhilRunninger** [comment]
@marcelned I won't be putting that in NERDTree. That functionality is provided by the **netrw** plugin, which ships with Vim, and I have no interest in, or time to spend on, duplicating it.

You can put these lines in your `.vimrc` as a way to have the functionality of both file browser plugins. It will open **netrw** if you specify a path starting with "scp://", either on the OS command line, or in Vim if you use this `:FileBrowse` command. It doesn't change the behavior of the `:e scp://....` command, so that would continue doing what it does now.

```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc()==1 && !exists('s:std_in') | if OpenFileBrowser(argv()[0]) | wincmd p | enew | wincmd p | endif | endif
nnoremap <C-P> :FileBrowser<CR>
command! -n=? -complete=dir -bar FileBrowser :call OpenFileBrowser('<args>')

function! OpenFileBrowser(...)
    if a:0 == 0 || a:1 == ''
        NERDTree
    elseif a:1 =~? '^scp://'
        execute 'Vexplore '.a:1
        return 1
    elseif isdirectory(a:1)
        execute 'NERDTree '.a:1
        return 1
    endif
    return 0
endfunction
```

**Comment by marcelned** [comment]
@PhilRunninger  works like a dream! thank you

**Comment by PhilRunninger** [comment]
Taking this a step further, you can use an abbreviation to replace the `:edit` command. Below are the updated statements, with proper comments. 

One thing I'm not sure of, and can't test right now, is how `filereadable()` treats remote files. If it recognizes them, the `:edit` command will undoubtedly fail. If it doesn't recognize remote files, I'm not sure what **netrw** will do when given a file instead of a directory. @marcelned , can you test the code below for me? (That's probably quicker than my setting up a working VM to test on.) What happens when you try `vim scp://user@remotehost//path/file` or `:Edit scp://user@remotehost//path/file`?

Thanks!

```vim
" Use netrw for remote files/directories, and NERDTree for everything else. {{{1

    " Function to open the file or NERDTree or netrw.
    "   Returns: 1 if a file explorer was opened; otherwise, 0.
    function! s:OpenFileOrBrowser(...)
        if a:0 == 0 || a:1 == ''
            NERDTree
        elseif filereadable(a:1)
            execute 'edit '.a:1
        elseif a:1 =~? '^\(scp\|ftp\)://' " Add other protocols as needed.
            execute 'Vexplore '.a:1
            return 1
        elseif isdirectory(a:1)
            execute 'NERDTree '.a:1
            return 1
        endif
        return 0
    endfunction

    " Auto commands to handle OS commandline arguments.
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc()==1 && !exists('s:std_in') | if <SID>OpenFileOrBrowser(argv()[0]) | wincmd p | enew | wincmd p | endif | endif

    " Command to call the OpenFileOrBrowser function.
    command! -n=? -complete=file -bar Edit :call <SID>OpenFileOrBrowser('<args>')

    " Key mapping to call Edit. With no arguments, this will open NERDTree.
    nnoremap <C-P> :Edit<CR>

    " Command-mode abbreviation to replace the :edit Vim command.
    cnoreabbrev e Edit

" }}}
```

**Comment by marcelned** [comment]
@PhilRunninger  I tested both `vim scp://user@remotehost//path/file` and `:Edit scp://user@remotehost//path/file`:

- `vim scp://user@remotehost//path/file` opens the file as desired, if `vim scp://user@remotehost//path/` is invoked, the path is indeed opened in **netrw**.
- `:Edit scp://user@remotehost//path/file` exhibits same behavior.

Brilliant stuff!

**Comment by PhilRunninger** [comment]
Awesome! I'll publish this in the README. Thanks for testing it for me.
