### ISSUE TITLE
How to close the preview opened with `go` from nerdtree ?

### ISSUE THREAD

**Issue by SarveshMD** [preservim/nerdtree#1256]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question

How to close the preview opened with `go` from nerdtree ?

**Comment by PhilRunninger** [comment]
@SarveshMD  There is nothing in NERDTree that will do that for you. However, the **nerdtree-buffer-ops** plugin (https://github.com/PhilRunninger/nerdtree-buffer-ops) adds that capability. With that plugin installed, from NERDTree you can type <kbd>go</kbd> to preview a file, and then <kbd>w</kbd> to close the buffer. The mnemonic for <kbd>w</kbd> is "**w**ipeout", because it uses Vim's `:bwipeout` command.
