### ISSUE TITLE
Navigating nerd tree from buffer

### ISSUE THREAD

**Issue by pnchinmay** [preservim/nerdtree#1258]
@scrooloose Thanks for this awesome tool.  
It has been in my workflow for quite some time and I absolutely love it.  

I was looking for some sort of vim like keybindings for navigating consecutive files in the directory without jumping back and forth between nerd tree and the buffer. Also, I've used the plugin of opening multiple files in nerd tree.  
I don't wish to preview the files and I've looked through the preview feature too. These don't suit my requirements.  
It's more of a quick editing of files in a directory. As of now, I'm using **@PhilRunninger's** nerd tree plugin for opening multiple files and then navigating through fzf buffers.
A demo for the above said feature is attached below.  

**A keybind for opening previous file and next file in the directory/nerd tree would suffice**
Kindly point me to the docs for the above said feature, if any.

https://user-images.githubusercontent.com/62750974/131730112-079a61cb-bbdf-40f9-99a7-5e62ec418620.mp4

**Comment by PhilRunninger** [comment]
@pnchinmay If you're using the default NERDTree mappings, you could use put this in your `.vimrc` file:
```vim
nmap <C-P> :NERDTreeFind<CR><C-J>o
```

Obviously you can change <kbd>Ctrl+P</kbd> to whatever you want. And if you changed the NERDTree key mappings, use those instead of <kbd>Ctrl+J</kbd> and <kbd>o</kbd>. Using <kbd>Ctrl+J</kbd> (or whatever you have set in `g:NERDTreeMapJumpNextSibling`) instead of <kbd>j</kbd> keeps you from leaving the directory.

**Comment by pnchinmay** [comment]
@PhilRunninger Thanks a lot.
This works perfectly. And a ton better than the earlier options.
