### ISSUE TITLE
Why do all my files appear executable when they are not in neovim?

### ISSUE THREAD

**Issue by zalvarez23** [preservim/nerdtree#1310]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+169-ge50b1fe60

### Vim (not Nvim) behaves the same?

vim  8.2

### Operating system/version

12.3.1 (21E258)

### Terminal name/version

iterminal

### $TERM environment variable

--

### Installation

..

### How to reproduce the issue

...

### Expected behavior

<img width="764" alt="image" src="https://user-images.githubusercontent.com/10501721/169772348-15a11788-f343-4680-b005-4c573b792938.png">

The files are displayed correctly without the asterisk and in the normal color.

### Actual behavior

<img width="765" alt="image" src="https://user-images.githubusercontent.com/10501721/169772294-c23bcfb8-ae35-4bf2-b94f-100f47ca4c70.png">

All files appear red and with asterisks.

**Comment by rzvxa** [comment]
Since the author of the issue hasn't replayed in a long time I'm going to close this issue.
PS: I've experienced this problem when moving files from a Windows machine to Linux as mentioned by @mattitk, I think there are some compatibility issues with the way NTFS handles the user access to to files.
If that's the case try to chmod them with the right permissions. NERDTree is just reflecting the current permissions of the file. use something like `chmod a-x file.js` or `chmod -R a-o parent_directory`.
