### ISSUE TITLE
NERDTree (vim9 Vundle) on Windows11 displays random folders with paths, and they can't be opened.

### ISSUE THREAD

**Issue by aziztovbaev** [preservim/nerdtree#1327]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question
Folder paths are displayed next to them, <folder name> -> <path to that folder>, and most of those folders can't be opened. Are there conf settings other than utf encoding and DirArrowExpandable/Collapsible?

**Comment by rzvxa** [comment]
Hi, Sorry for the late response to this issue, I was checking older issues and this one seems to have gone unnoticed. Those files with `->` in their names are shortcuts/symlinks, Most probably those files are created by Windows itself and that's why you don't have permission to edit them.
You can use `:help NERDTree` in vim to open the documentation for the NERDTree.
