### ISSUE TITLE
NERDTree only opens on the first tab when opening few files with vim -p

### ISSUE THREAD

**Issue by dnl0** [preservim/nerdtree#1343]
#### Self-Diagnosis

- [x] - i have searched [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- [x] - i have read NERDTree documentation - `:h NERDTree`
- [x] - i have checked [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- [x] - i have seen other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: MacOS
- Vim/Neovim version `:version`: NVIM v0.8.0
- NERDTree version, found on first line of quickhelp `?`: NERDTree 6.10.16
- Are you using any of these NERDTree-dependent plugins?  No
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
" NERDTree
autocmd StdinReadPre * let s:std_in=1
" Start NERDTree and put cursor on other window
autocmd VimEnter * NERDTree % | wincmd p
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif
" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
" Close the tab if NERDTree is the only window remaining in it.
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
" Default position
let g:NERDTreeWinPos = "right"
" Mouse mode
let g:NERDTreeMouseMode=1
" Width
let g:NERDTreeWinSize=30
```

#### Steps to Reproduce the Issue
1. open few files with `nvim -p <file1> <file2>`
2. head over to second file

#### Current Behavior (Include screenshots where appropriate.)
NERDTree opens on the first tab
<img width="847" alt="image" src="https://user-images.githubusercontent.com/61200897/213392529-70562ea7-4cac-4a09-a074-11141d6e33ec.png">

Doesn't open on the second tab
<img width="848" alt="image" src="https://user-images.githubusercontent.com/61200897/213392624-23701037-623a-45be-abfa-1811b2ddd2be.png">

#### Expected Result
NERDTree opens for each tab

#### Additional notes
When entering `:NERDTree` on the second tab two instances of NERDTree opens
<img width="845" alt="image" src="https://user-images.githubusercontent.com/61200897/213393218-d9eb0ef8-c80c-4926-9544-c9f3ad5b22d8.png">

Also note that NERDTree opens as expected when using `:tabnew`

**Comment by rzvxa** [comment]
Hi,

As far as I can tell it's not a bug, You just need to modify your configuration to get it to work.
But I highly encourage you to invest time to get comfortable with the concept of buffers instead, In general vim doesn't like tabs, As they are more of a layout preset than tabs in other software, You should use buffers where you would use tabs in other IDEs and editors, And only use tabs if you want to for example have 2 buffers side by side in one tab and have them stacked on top of each others in another so you can quickly switch between these 2 views.

Back to the problem, I think if you use `:NERDTreeToggle` instead of `:NERDTree`, It would work, I can't 100% reproduce your problem But it will fix the problem with 2 instances instead of opening the mirrored tree.
