### ISSUE TITLE
NERDTree is affecting the jumplist

### ISSUE THREAD

**Issue by ajwrigley** [preservim/nerdtree#1349]
When editing a file I frequently use CTRL-o and CTRL-i to navigate through previous cursor positions. But NERDTree is adding entries to the jumplist so CTRL-o does weird things like opening another instance of NERDTree in the main buffer.

Is there a workaround for this, to prevent any NERDTree entries from going into the jumplist?

**Comment by rzvxa** [comment]
@ajwrigley I've been trying to fix this for a while, Sadly there is no real way of getting rid of it. You can mark the buffer as hidden to prevent it from coming up in the jumplist but it does break other functionalities.
Even Vim's built-in file explorer `netrw` has this gimmick, I'm going to mark it as not planned since even if it is possible to fix it needs a huge time investment and doesn't really provide enough value to anyone's workflow.

Don't let my reasoning discourage you from fixing it and creating a PR addressing this issue, I would welcome such change and I'll even help you in the process if you get stuck anywhere.
