### ISSUE TITLE
Unable to open file on newly opened tree after the default tree is closed

### ISSUE THREAD

**Issue by smptmhr** [preservim/nerdtree#1374]
---

#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: macOS 12.5.1
- Vim/Neovim version `:version`: 8.2.5032
- NERDTree version, found on first line of quickhelp `?`: 6.10.16
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
filetype off

if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim
    call neobundle#begin(expand('~/.vim/bundle/'))
    "insert here your Neobundle plugins"
    NeoBundle 'scrooloose/nerdtree'
    call neobundle#end()
endif

nnoremap <silent><C-e> :NERDTreeToggle<CR>
let NERDTreeWinSize=26
```

#### Steps to Reproduce the Issue
1. move to directory which has one or more files
```
cd directory_name
```
2. Open vim on the directory
```
vi .
```
3. open a new tree
```
Ctrl + E
```
4. close the left tree(confirm cursor is on the left tree)
```
:q
```
5. move cursor to any file
6. open file by "s" key
```
s
```

#### Current Behavior (Include screenshots where appropriate.)
Error occured as below.
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..86[18]..85[3]..<SNR>27_openVSplit[1]..115[1]..131[3]..187[6]..188[9]..182[3]..186[16]..227[1]..237[2]..function nerdtree#ui_glue#invokeKe
yMap[1]..86[18]..85[3]..<SNR>27_openVSplit[1]..115[1]..131[3]..187[6]..188[9]..182[3]..186[16]..227[1]..237:
line    2:
E605: Exception not caught: NERDTree.TreeNotOpen
Press ENTER or type command to continue
```

screenshot
<img width="1920" alt="スクリーンショット 2023-10-17 18 43 32" src="https://github.com/preservim/nerdtree/assets/84895022/5a39f69e-b694-4c73-986f-ff4293b08e24">

#### Expected Result
The selected file is successfully opened.

#### additional information
Error does not occur with following steps.

1. move to directory which has one or more files
```
cd directory_name
```
2. Open vim on the directory
```
vi .
```
3. open a new tree
```
Ctrl + E
```
4. move cursor to the tree on right side
```
ctrl + w + w
```
5. close the right tree(confirm cursor is on the right tree)
```
:q
```
6. move cursor to any file
7. open file by "s" key
```
s
```
8. successfully opend

**Comment by rzvxa** [comment]
Hello,

I'm currently working on another issue and my vim setup is in the middle of developing a fix for that problem.
I just wanted to let you know that I'm gonna work on it as soon as I get the other PR done and also I managed to get the error on my Linux machine so It is not a Mac-specific problem and I can debug it without borrowing one from my work.
Meanwhile, You can use NERDTreeToggle for closing the tree instead of using `:q`, I'm not sure how exactly this part of NERDTree works as I never touched that section of the code.
Another quick fix without fixing the actual issue would be adding this to your .vimrc:
```vim
" Start NERDTree when Vim starts with a directory argument.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ execute 'NERDTree' argv()[0] | wincmd p | enew | execute 'cd '.argv()[0] | endif
```

By using that snippet in your config you would potentially prevent NERDTree from spawning 2 instances instead of one when opening a directory with it.

I'll share more information with you on this thread as soon as I learn more about this undesired behavior. But if I had to guess I would say on `:q` we set the global (global to the tab not the whole instance of vim) reference of NERDTree to null and that's why we cannot open the file in the other NERDTree.

By the way let me know if the solutions I've mentioned above fix your problem or not, Maybe we don't really need to spend time on this issue if the outcome from those solutions are desirable enough.

**Comment by rzvxa** [comment]
@smptmhr sorry for pinging you on this issue, Have you found my reply to resolve your problem? If that's the case let me know so we can close it.

**Comment by smptmhr** [comment]
@rzvxa 
thanks for replaying.
By adding your script to my `.vimrc`, only one tree instanse can open and my problem was solved!

**Comment by rzvxa** [comment]
Great to hear that solved the issue, have a nice rest of the day.
