### ISSUE TITLE
Customize key to open quick help menu

### ISSUE THREAD

**Issue by MatthewUng** [preservim/nerdtree#1396]
#### Description

I would like to customize the key to open the quick help menu in NERDTree away from `?` as `?` is often used for reverse search.

**Comment by rzvxa** [comment]
@MatthewUng I use `/` with `n` and `N` for reverse search so it never really bothered me personally, But I'm sure there are many people who use `?` all day long so I understand that the original choice of using `?` as a key bind hasn't aged that well, 
I think changing it to `g?` would be a good candidate for the new default since the NERDTree buffer isn't modifiable so nobody can use it in this buffer anyway, and it also resembles the `go to help` notion.

All that said, I'm not sure whether adding a new customizable option is the best approach or not.

**Comment by MatthewUng** [comment]
Understood.  Changing the key away from `?` to `g?` or even `h` to keep it one char long would solve my issue.
If we settle on a decision, I'd be happy to put up the change.

**Comment by rzvxa** [comment]
> Understood. Changing the key away from `?` to `g?` or even `h` to keep it one char long would solve my issue. If we settle on a decision, I'd be happy to put up the change.

Sorry it took me a few hours, I had to check the source code to make sure, And a good thing I did, Turns out it is already customizable and I wasn't aware of it since I've never considered changing it in my own config. Just assign the `NERDTreeMapHelp` variable in your config to change it to whatever is appropriate to your use case.
