### ISSUE TITLE
BUG: NERDTree Hijacked Movement Keys

### ISSUE THREAD

**Issue by Swivelgames** [preservim/nerdtree#1399]
A recent change in #1384 conflicts with a common navigation style for hopping up and down the buffer.

# Reproduction Steps

1. Open a large project in VIM
2. Show NERDTree
3. Attempt to navigate to the bottom of the buffer with `L`

## Expected Behavior

Caret jumps to the bottom of NERDTree's buffer

## Actual Behavior

NERDTree displays Number of Lines next to files

-----------

This breaks consistency among buffers, especially for something as fundamental as navigation.

**Comment by Swivelgames** [comment]
This is pretty significant for me, personally, since I use a combination of `H`,`M`, or `L` and `zt` or `zb` for scrolling, along with the former for just basic buffer navigation.

This is equivalent to remapping h, j, k, or l

**Comment by Swivelgames** [comment]
Just saw @isaiah's comment on #1384 asking for the removal or change of this keybinding as well:

> The keybinding override the navigation shortcut to move the cursor to the bottom, which is very important, is it possible to disable the keybinding?

**Comment by rzvxa** [comment]
Hey, Thanks for reporting this issue.

For now, you can use the `g:NERDTreeMapToggleFileLines` variable to change it to something else so you can move on with your work until we change the default to prevent clashing with `L` binding.
Let me know if you have any good suggestions for this keybind, otherwise, I'm going to just use a 2 letter keybind as default.
I'm sorry for this inconvenience, I personally don't use `H`, `L`, or `M` in the context of NERDTree so I just didn't think about this. To be honest I just chose `L` without putting that much thought into it otherwise I would've averted this issue before it affected anyone.

**Comment by Swivelgames** [comment]
Honestly, when I saw it, I figured that's what happened hahah. "L = Line Numbers" makes sense. I actually use H, M, and L subconsciously, so I wasn't even sure what happened until I tried to do it a second or third time. I was very confused 😅

**Comment by Swivelgames** [comment]
Just updated, and it works beautifully! Thanks again!

**Comment by rzvxa** [comment]
@Swivelgames No worries mate, It was my pleasure.
