### ISSUE TITLE
Installing NERDTree with Vim 9 on Windows 10

### ISSUE THREAD

**Issue by russurquhart1** [preservim/nerdtree#1402]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question

I've looked around and haven't found any working answers. I tried to use Vim8+ builtin plugin manager and that didn't work. I tried moving the files and folders from Doc, Nerdtree_plugin, and plugin to my vimrc file but that just gave a series of errors. 

Can someone explain to me how to install this. I'd rather not use a third-party plugin manager if possible.

Thanks,

Russ

**Comment by rzvxa** [comment]
Hi,
On the readme file, there is a link to [this YouTube video](https://www.youtube.com/watch?v=X2_R3uxDN6g) which explains how to use the Vim packages. You can also use the `:help packages` to open up the documentation for them.
I respect your decision not to use a third-party plugin manager, But I personally like them more since Vim packages are too bare-bone for my liking. A plugin manager can easily integrate with git, and have additional features missing in the Vim packages.

For example `vim-plug` supports loading plugins on demand(lazily) and if you configure it like this:

```vim
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
```

It will only load the plugin when the NERDTreeToggle command is used. Or you can have some plugins only loaded when certain file types have been opened with something like this:

```vim
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
```

**Comment by russurquhart1** [comment]
Hi, I actually watched that same video this morning, before I started trying to use Vim packages. I thought I put all the files in the right location, as per the video, but I'll check about it again. As far as what parts of the NERDTree repo are needed, correct me if I'm wrong, but it is only the doc, nerdtree_plugin, and plugin directories that are needed, correct?

**Comment by russurquhart1** [comment]
I got it to work, I was not aware that you have to put, for a given plugin repo, a clone of that repo in the start directory.

However, once it started I got an:
NERDTree: 3 Invlaid file(s): NTUSER.DAT, ntuser.dat.LOG1, ntuser.datLOG2

Any idea what that error means or how to get rid of it?

Thanks

**Comment by rzvxa** [comment]
> I got it to work, I was not aware that you have to put, for a given plugin repo, a clone of that repo in the start directory.

That's great news!

> However, once it started I got an:
> NERDTree: 3 Invlaid file(s): NTUSER.DAT, ntuser.dat.LOG1, ntuser.datLOG2
>
> Any idea what that error means or how to get rid of it?

This has nothing to do with your setup, Nerdtree will warn about files that failed to load properly. These files mentioned here belong to Windows and you probably just don't have enough permission to read them.

[I've seen this error reported](https://github.com/preservim/nerdtree/issues/1253#issuecomment-1772971733) before but it doesn't happen on my Windows machine and since I have administrator access on that machine I've suspected that it has to do with the access restrictions.
When it was mentioned in the issue linked above, I did some research on the internet and found no real solution for it. As far as I know on some Windows machines these files are restricted and attempting to read them will result in an error.

You can do some research yourself in case there is a new post on the Microsoft support forums or maybe I have missed something before.
While these warnings at the start are a little bit annoying they only happen when you open NERDTree in your home directory(as it is the directory containing the restricted files) and since these files aren't supposed to be edited directly I suggest you just ignore them.
