### ISSUE TITLE
Installation???

### ISSUE THREAD

**Issue by seamusdemora** [preservim/nerdtree#1406]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question

Your README file offers several  - what I think are called - *plugin managers* as a means for installation. I'm sure they're great, but I'm trying to minimize clutter on my tiny Raspberry Pi. I **read somewhere** (can no longer find the reference) that `NERDtree` could be installed as follows:

```bash
$ git -C ~/.vim/pack/others/opt clone https://github.com/preservim/nerdtree
Cloning into 'nerdtree'...
remote: Enumerating objects: 6236, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 6236 (delta 105), reused 179 (delta 67), pack-reused 6008
Receiving objects: 100% (6236/6236), 1.94 MiB | 5.34 MiB/s, done.
Resolving deltas: 100% (2840/2840), done.
``` 

As you can see, it *seems* to have been installed, but when I start `vim`, I get an error message:
```
Error detected while processing VimEnter Autocommands for "*":
E492: Not an editor command: NERDTree | wincmd p" Start NERDTree and put the cursor back in the other window.
```

Here's the contents of `~/.vimrc`: 
```
" Start NERDTree and put the cursor back in the other window.
autocmd VimEnter * NERDTree | wincmd p" Start NERDTree and put the cursor back in the other window.
autocmd VimEnter * NERDTree | wincmd p
" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
```

**Comment by seamusdemora** [comment]
@rzvxa 
Yes - I was (and still am) unclear on the distinctions between opt & start. But I've rm'd from opt & re-git'd in start - and seems all is well now. 
Thank you!

**Comment by rzvxa** [comment]
I'm glad to hear that. Just to make myself clear, I will explain an example where the opt directory and optional plugins may help.

The plugins placed under the `opt` directory won't load at the start and you should load them using the `packadd` command. this gives you the ability to have some plugins specifically for certain situations. For example, I can have a plugin for working with `.md` files and have an autocmd in my configuration to only load this plugin when I'm reading a `.md` file. Since most of the time I'm not working with md files loading the plugin lazily would save more resources and provide flexibility to keep some plugins confined to certain workspaces.

I personally use lazy plugins(optional) for things like code formatting since each file type needs its own formatter.
You may not find a use for it right now but knowing that it is possible would come in handy in the future when you actually find a place for it.

**Comment by seamusdemora** [comment]
It may interest you to know that you and your comment have earned a place in my personal "vim cheat sheet"  :o  

Seriously though,  "Thanks again" :)
