### ISSUE TITLE
should no error when exe NERDTreeFind for file in a linked directory

### ISSUE THREAD

**Issue by SolaWing** [preservim/nerdtree#884]
### Environment

* Operating System: MAC
* Vim version `:version`:  nvim v0.3.1
* NERDTree version `git rev-parse --short HEAD`: newest: 808f5b2

### Process

1. Given a file `/tmp/A/a.txt`, and a link `/tmp/B -> /tmp/A`
2. enter vim, and exe: `:edit /tmp/B/a.txt`
3. then exe: `:NERDTreeFind`

### Current Result

Throw Exception: 
```
处理 function <SNR>9_lod_cmd[3]..<SNR>110_findAndRevealPath[40]..161 时发生错误:
第    4 行:
E605: 异常没有被捕获: NERDTree.InvalidArgumentsError: /tmp/B/a.txt should be under /private/tmp/A
```
### Expected Result

No Exception

**Comment by PhilRunninger** [comment]
I can reproduce this error without the linked folder `B`. I get the same message with `:edit /tmp/A/a.txt` and `:NERDTreeFind`. It must be happening because `/tmp/ ` is a link that points to `/private/tmp`.

*Note to self:* Look for the `resolve()` function invocations. I'm guessing it needs to be done on the filename `/tmp/A/a.txt` before looking for it under `/private/tmp/A`.
